name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare dotnet
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Prepare Clojure CLR
        run: |
          dotnet tool install --global Clojure.Main --version 1.12.0-alpha10
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha5
      - name: Run cljr tests
        run: cljr -X:test